---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: cluster-network-configs
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    directory:
      include: '{*.yaml,*.yml}'
      recurse: true
    path: artifacts/infrastructure/cluster-network-configs
    repoURL: https://github.com/nandiheath/zaap
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
