---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      jqPathExpressions:
        - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
  project: default
  revisionHistoryLimit: 10
  source:
    directory:
      include: '{*.yaml,*.yml}'
      recurse: true
    path: artifacts/infrastructure/istiod
    repoURL: https://github.com/nandiheath/zaap
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
      - Validate=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
