apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    releaseName: cilium
    namespace: kube-system
    version: 1.18.0
    valuesInline:
      # The IP for the Kubernetes API server.
      k8sServiceHost: 10.43.2.1
      k8sServicePort: 6443
      kubeProxyReplacement: true
      socketLB:
        hostNamespaceOnly: true
      # avoid configuration conflicts with istio ambient mode
      # https://docs.cilium.io/en/latest/network/servicemesh/istio/
      cni:
        exclusive: false
      hubble:
        tls:
          auto:
            method: certmanager
            certValidityDuration: 1095
            certManagerIssuerRef:
              group: cert-manager.io
              kind: ClusterIssuer                
              name: selfsigned
      ipam:
        operator:
          clusterPoolIPv4PodCIDRList:
            - "10.45.0.0/16"
            