---
apiVersion: v1
data:
  AMBIENT_DNS_CAPTURE: "false"
  AMBIENT_ENABLED: "true"
  AMBIENT_IPV6: "true"
  CHAINED_CNI_PLUGIN: "true"
  CURRENT_AGENT_VERSION: 1.24.5
  EXCLUDE_NAMESPACES: kube-system
  REPAIR_BROKEN_POD_LABEL_KEY: cni.istio.io/uninitialized
  REPAIR_BROKEN_POD_LABEL_VALUE: "true"
  REPAIR_DELETE_PODS: "false"
  REPAIR_ENABLED: "true"
  REPAIR_INIT_CONTAINER_NAME: istio-validation
  REPAIR_LABEL_PODS: "false"
  REPAIR_REPAIR_PODS: "true"
kind: ConfigMap
metadata:
  labels:
    app: istio-cni
    app.kubernetes.io/instance: istio-cni
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-cni
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.24.5
    helm.sh/chart: cni-1.24.5
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: default
    operator.istio.io/component: Cni
    release: istio-cni
  name: istio-cni-config
  namespace: kube-system
