---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-server-certs
  namespace: kube-system
spec:
  commonName: '*.default.hubble-grpc.cilium.io'
  dnsNames:
    - '*.default.hubble-grpc.cilium.io'
  duration: 26280h0m0s
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
  privateKey:
    rotationPolicy: Always
  secretName: hubble-server-certs
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
