apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-admin
  namespace: postgresql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: postgresql-admin
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: postgresql-admin
        property: user-password
      secretKey: user-password
