apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - external-secret.yaml

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: postgresql
    namespace: postgresql
    version: 16.7.26
    valuesInline:
      global:
        postgresql:
          auth:
            existingSecret: postgresql-admin
            secretKeys:
              adminPasswordKey: password
              userPasswordKey: user-password
              replicationPasswordKey: password
      primary:
        persistence:
          existingClaim: postgresql-data
        
      readReplicas:
        count: 0
