apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: istio-public-ingressgateway
    app.kubernetes.io/instance: istio-public-ingressgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-public-ingressgateway
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.24.5
    helm.sh/chart: gateway-1.24.5
    istio: public-ingressgateway
  name: istio-public-ingressgateway
  namespace: istio-system
