---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cloudflare-tunnel
        metadataPolicy: None
        property: credentials.json
      secretKey: credentials.json
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
