apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zaap-nandi-sh-cert
  namespace: istio-system
spec:
  secretName: zaap-nandi-sh-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - zaap.nandi.sh