apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # installation of Metallb
  - github.com/metallb/metallb/config/native?ref=v0.14.9
  - ip-address-pool.yaml
  - advertisement.yaml
