apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    namespace: argocd
    additionalValuesFiles:
      - values.yaml
    version: "8.2.2"
