---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  annotations:
    postgresql.io/extensions: pgvecto.rs
  labels:
    app.kubernetes.io/component: postgres-database-credentials
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/version: v1.119.0
  name: postgresql-credentials-immich
  namespace: immich
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-credentials-immich
        metadataPolicy: None
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-credentials-immich
        metadataPolicy: None
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-credentials-immich
        metadataPolicy: None
        property: database
      secretKey: database
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: postgresql-credentials-immich
        metadataPolicy: None
        property: connection-url
      secretKey: connectionURL
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
