apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

helmCharts:
- name: gateway
  repo: https://istio-release.storage.googleapis.com/charts
  releaseName: istio-public-ingressgateway
  namespace: istio-system
  version: 1.24.5
  valuesFile: values.yaml

# should wait until CRD and admission webhook starts first
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/

