---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx
spec:
  gateways:
    - istio-system/istio-ingressgateway
  hosts:
    - zaap.nandi.sh
  http:
    - match:
        - uri:
            prefix: /test-app
      route:
        - destination:
            host: nginx
            port:
              number: 80
