apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    path: artifacts/infrastructure/cert-manager
  destination:
    namespace: cert-manager
