apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  annotations:
    # update at last (this should be installed first during bootstrap tho)
    argocd.argoproj.io/sync-wave: "5"
spec:
  source:
    path: artifacts/infrastructure/cilium
