apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  source:
    path: artifacts/infrastructure/cluster-namespaces
