apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  annotations:
    # apply after istiod being updated
    argocd.argoproj.io/sync-wave: "1"
spec:
  source:
    path: artifacts/infrastructure/istio-base
  destination:
    namespace: istio-system
  ignoreDifferences:
    # https://github.com/istio/istio/issues/52785
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jqPathExpressions:
        - .webhooks[] | select(.name == "validation.istio.io") | .failurePolicy