apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  annotations:
    # apply after istio-base being updated
    argocd.argoproj.io/sync-wave: "2"
spec:
  source:
    path: artifacts/infrastructure/istio-cni