apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  annotations:
    # apply at last
    argocd.argoproj.io/sync-wave: "5"
spec:
  source:
    path: artifacts/infrastructure/prometheus
  
