apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    namespace: longhorn
    version: 1.9.1
    valuesInline:
      preUpgradeChecker:
        jobEnabled: false
      longhornManager:
        log:
          format: json
      longhornDriver:
        log:
          format: json
      longhornUI:
        replicas: 1