apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-credentials-immich
  namespace: immich
  labels:
    app.kubernetes.io/component: postgres-database-credentials
  annotations:
    # allows the script to read the extension and install them
    postgresql.io/extensions: "pgvecto.rs"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: postgresql-credentials-immich
        property: password
      secretKey: password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: postgresql-credentials-immich
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: postgresql-credentials-immich
        property: database
      secretKey: database
