apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml

helmCharts:
  - name: immich
    repo: oci://ghcr.io/immich-app/immich-charts
    releaseName: immich
    namespace: immich
    version: 0.9.3
    valuesInline:
      immich:
        persistence:
          library:
            existingClaim: immich-library
      
