---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: cloudflare-api-token
        metadataPolicy: None
        property: api-token
      secretKey: cloudflare-api-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
