apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: immich
  namespace: immich
spec:
  hosts:
    - "immich.nandi.sh"
  gateways:
    - istio-system/ingress-gateway
  http:
    - route:
        - destination:
            host: immich-server
            port:
              number: 2283
