apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: cni
  repo: https://istio-release.storage.googleapis.com/charts
  releaseName: istio-cni
  namespace: kube-system
  version: 1.24.5
  includeCRDs: true
  valuesInline:
    cni:
      enabled: true
    ambient:
      enabled: true
    profile: ambient
    global:
      platform: k3s

